config/routes.rb
Pip::Application.routes.draw do
  
  resources :tags

  resources :meetings do
    resources :talks
  end

  resources :users

  root :to => 'pages#home'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  has_many :talks
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.haml
= form_for(@meeting) do |f|
  - if @meeting.errors.any?
    #error_explanation
      %h2
        = pluralize(@meeting.errors.count, "error")
        prohibited this meeting from being saved:
      %ul
        - @meeting.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :when
    %br/
    = f.date_select :when
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/meetings/edit.html.haml
%h2 Editing meeting
= render 'form'
= link_to 'Show', @meeting
\ |
= link_to 'Back', meetings_path

%hr

- @meeting.talks.each do |talk|
  = talk.title
  %br

%hr
- @talk = Talk.new
= form_for @talk, :url => meeting_talks_path(@meeting) do |f| 
  -if @talk.errors.any? 
    #error_explanation
      %h2= pluralize(@talk.errors.count, "error")  + "prohibited this talk from being saved:"
      %ul
        - @talk.errors.full_messages.each do |msg| 
          %li= msg

  .field
    = f.label :user
    %br
    = f.text_field :user 

  .field
    = f.label :title
    %br
    = f.text_field :title 
  
  .field
    = f.label :description
    %br
    = f.text_area :description 
  
  .field
    = f.label :tag_list
    %br
    = f.text_field :tag_list 
  
  .actions
    = f.submit
    

app/views/meetings/index.html.haml
%h1 Listing meetings
%table
  %tr
    %th When
    %th Description
    %th
    %th
    %th
  - @meetings.each do |meeting|
    %tr
      %td= meeting.when
      %td= meeting.description
      %td= link_to 'Show', meeting
      %td= link_to 'Edit', edit_meeting_path(meeting)
      %td= link_to 'Destroy', meeting, confirm: 'Are you sure?', method: :delete
%br/
= link_to 'New Meeting', new_meeting_path

app/views/meetings/new.html.haml
%h1 New meeting
= render 'form'
= link_to 'Back', meetings_path

app/views/meetings/show.html.haml
%p#notice= notice
%p
  %b When:
  = @meeting.when
%p
  %b Description:
  = @meeting.description
= link_to 'Edit', edit_meeting_path(@meeting)
|
\#{link_to 'Back', meetings_path}